### ISSUE TITLE
uninitialized constant Ably::Models::MessageEncoders

### ISSUE THREAD

**Issue by szyablitsky** [ably/ably-ruby-rest#3]
gem version 0.9.2
```
/home/finch/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'ably-rest'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant Ably::Models::MessageEncoders
Backtrace for gem load error is:
/home/finch/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ably-rest-0.9.2/lib/submodules/ably-ruby/lib/ably/models/presence_message.rb:56:in `<class:PresenceMessage>'
/home/finch/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ably-rest-0.9.2/lib/submodules/ably-ruby/lib/ably/models/presence_message.rb:40:in `<module:Models>'
/home/finch/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ably-rest-0.9.2/lib/submodules/ably-ruby/lib/ably/models/presence_message.rb:1:in `<top (required)>'
/home/finch/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ably-rest-0.9.2/lib/submodules/ably-ruby/lib/ably/rest.rb:7:in `block in <top (required)>'
/home/finch/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ably-rest-0.9.2/lib/submodules/ably-ruby/lib/ably/rest.rb:6:in `each'
/home/finch/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ably-rest-0.9.2/lib/submodules/ably-ruby/lib/ably/rest.rb:6:in `<top (required)>'
/home/finch/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/ably-rest-0.9.2/lib/ably-rest.rb:24:in `<top (required)>'
/home/finch/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `require'
```
I got this error on my home workstation, but strangely everything is working fine on my office workstation and production server.

Quick fixed it by adding
```
Dir.glob(File.expand_path("models/message_encoders/*.rb", File.dirname(__FILE__))).each do |file|
  require file
end
```
before
```
Dir.glob(File.expand_path("models/*.rb", File.dirname(__FILE__))).each do |file|
  require file
end
```
in `lib/submodules/ably-ruby/lib/ably/rest.rb`

**Comment by mattheworiordan** [comment]
Thanks for reporting, will investigate today and get a fix out once I understand what's happening. Out of interest, what platform did you get this error on?

**Comment by mattheworiordan** [comment]
@szyablitsky I have just released `0.9.3` which I believe resolves the dependency issue.  Sorry for the inconvenience.  Please can you try `0.9.3` to confirm if this issue is now resolved for you?

**Comment by mattheworiordan** [comment]
@szyablitsky did you manage to try this out?

**Comment by szyablitsky** [comment]
Hi, Matthew! Thank you for your efforts.
I already updated gem in project and it is working great as it was before.
But I'm usually working from home only on weekends when needed. I did not have time to check it out in home environment yet.
BTW my home and office envs are the same: Ubuntu 16.04, ruby 2.3.3 (via rbenv)

**Comment by mattheworiordan** [comment]
Great to hear that it worked, shout if you hit any issues!

**Comment by szyablitsky** [comment]
Tested last version at home. All is working fine. Thanks!
